#!/bin/bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
BOLD='\033[1m'
RESET='\033[0m' # Reset color

PROGRAM="findBlocks"

echo -e "$BOLD$CYAN==> Please enter the complete path to inputs folder: $RESET"
read PATH_INPUTS

cd src/

# Compile if it hasn't yet
if [[ -f $PROGRAM ]]; then
    echo -e "$BOLD$GREEN==> Program is already compiled. File $PROGRAM exists.$RESET"
else
    echo -e "$BOLD$YELLOW==> File $PROGRAM does not exist. Compiling...$RESET"
    make
fi

for i in $(ls $PATH_INPUTS); do
    # Print "x" yellow asterisks
    printf "$BOLD$YELLOW%0.s*${RESET}" {1..80}
    echo -e "\n$BOLD$GREEN==> Running $PROGRAM for input $i $RESET"
    ./$PROGRAM $PATH_INPUTS/$i 
    sleep 0.5   
done